backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - label: 'pages'
    name: 'pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'content/about.md'
        format: 'frontmatter'
        fields:
          - { label: Body EN, name: body_en, widget: markdown }
          - { label: Body RU, name: body_ru, widget: markdown }