backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - label: 'Pages'
    label_singular: 'Page'
    name: 'pages'
    create: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'content/about.md'
        format: 'frontmatter'
        fields:
          - { label: Body EN, name: body_en, widget: markdown }
          - { label: Body RU, name: body_ru, widget: markdown }
  - label: 'Steps'
    label_singular: 'Step'
    name: 'steps'
    folder: content/steps
    format: 'frontmatter'
    slug: '{{slug}}'
    identifier_field: uuid
    fields:
      - { label: 'UUID', name: 'uuid', widget: uuid }
      - { label: 'Duration', name: 'duration', widget: 'string', default: '100' }
      - { label: 'Order', name: 'order', widget: "number", value_type: "int", default: 0, step: 1 }
      - { label: 'Body EN', name: 'body_en', widget: markdown }
      - { label: 'Body RU', name: 'body_ru', widget: markdown }

